# Etapa de construção com o SDK 8.0
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Definindo o diretório de trabalho
WORKDIR /app

# Copiar os arquivos do projeto para o contêiner
COPY . . 

# Restaurar as dependências do projeto
RUN dotnet restore

# Compilar e publicar a aplicação para o diretório de saída
RUN dotnet publish -c Release -o out

# Etapa de runtime com a imagem base do ASP.NET 8.0
FROM mcr.microsoft.com/dotnet/aspnet:8.0

# Definindo o diretório de trabalho no contêiner final
WORKDIR /app

# Copiar a aplicação publicada para o contêiner
COPY --from=build /app/out .

# Definir o comando para rodar a aplicação
ENTRYPOINT ["dotnet", "Desafio_Tecnico_Cadastro_de_Beneficiarios.dll"]
